= Java 26
:toc:
:toc-placement:
:toclevels: 3
:icons: font

Java 26 will be released on the 17th of March 2026, and once again it helps move the language forwards.

[NOTE]
.Teaser of enhancements
====

====

== Why Upgrade?

Java 26 offers enterprises:

== Core

=== https://openjdk.org/jeps/500[JEP 500: Prepare to Make Final Mean Final]

When deep reflection's used to mutate final fields, warnings will be issued. The intent is to help developers prepare for future releases where this is restricted to help make our programs safer and maybe faster. (see for reference: https://openjdk.org/jeps/8305968[integrity by default]).

[,console]
----
WARNING: Final field foo in x.Y has been [mutated/unreflected for mutation] by class dev.simonverhoeven.z.caller in module Foo (file:/path/to/somefile.jar)
WARNING: Use --enable-final-field-mutation=N to avoid a warning
WARNING: Mutating final fields will be blocked in a future release unless final field mutation is enabled
----

API developers can avoid the current warnings and future restrictions by selectively enabling final field mutation where it's essential.

To enable final field mutation by any code on the class path regardless of where the field's declare we can use the command-line option: `--enable-final-field-mutation=ALL-UNNAMED`.

In case we want to be a bit more fine-grained, we can restrict it to specific modules by using: `--enable-final-field-mutation=module1, module2`
Do keep in mind that the to be mutated field must also be open to the code that's performing the deep-reflection.

Besides passing in the final-field option directly to the launcher as an option, there are other ways:

* using an argument-file
* setting `JDK_JAVA_OPTIONS`
* adding it to the manifest of an executable JAR
* through the `JNI Invation API` passing the option to an embedded JVM that it creates
* passing it to `jlink` when creating a custom Java runtime

We can also control what action the Java runtime takes when an illegal mutation is attempted:

* `--illegal-final-field-mutation=allow` will allow it without warnings
* `--illegal-final-field-mutation=warn` which is the default in JDK26 will allow it with a warning
* `--illegal-final-field-mutation=debug` will behave the same as warn, but wil also issue a stack trace
* `--illegal-final-field-mutation=deny` will result in `Field::set` throwing an `IllegalAccessException`. This will become the default in a future release

To help facilitate finding code that mutates final fields it's recommended to use `--illegal-final-field-mutation=debug` and/or use the Java Flight Recorder and look for `jdk.FinalFieldMutation` events.

[,console]
----
$ java -XX:StartFlightRecording:filename=catchmutation.jfr ...
$ jfr print --events jdk.FinalFieldMutation catchmutation.jfr
----



=== https://openjdk.org/jeps/504[JEP 504: Remove the Applet API]

The `Applet` API which was deprecated in JDK 17 through https://openjdk.org/jeps/398[JEP 398].
Generally speaking this will have a negligible impact given that web browsers no longer support applets.

The following will be removed:

* `java.applet` package
* `java.beans.AppletInitializer`
* `javax.swing.JApplet`

Additionally, references to the above will be removed from:

* `java.beans.Beans`
* `javax.swing.RepaintManager`

=== https://openjdk.org/jeps/517[JEP 517: HTTP/3 for the HTTP Client API]

The https://en.wikipedia.org/wiki/HTTP/3[HTTP/3 protocol] will now be supported by the https://cr.openjdk.org/~dfuchs/8291976/apidoc.04/api/java.net.http/java/net/http/HttpClient.html[HTTP Client API], allowing us to easily interact with HTTP/3 servers with minimal changes.
The https://en.wikipedia.org/wiki/QUIC[QUIC protocol] will not receive an API through this JEP, nor a sever-side implementation.

This can be done for all requests by configuring it on the HttpClient object:

[source,Java]
----
HttpClient client = HttpClient.newBuilder()
   .version(HttpClient.Version.HTTP_3)
   .build();
----

Or on a request basis:

[source,Java]
----
HttpRequest request = HttpRequest.newBuilder(URI.create("https://github.com/SimonVerhoeven/java26-demo"))
                         .version(HttpClient.Version.HTTP_3)
                         .GET().build();
----

=== https://openjdk.org/jeps/525[JEP 525: Structured Concurrency (Sixth Preview)]

This proposal aims to address some of the frequently encountered challenges in concurrent programming by introducing an API that treats groups of related tasks running in different threads as a single unit of work.

The proposed approach, also known as structured concurrency, will help us streamline error handling, cancellation, and observability, making concurrent code more reliable and easier to manage.

The main target is promoting a style of concurrent programming that eliminates common risks such as thread leaks and cancellation delays, while also improving the observability of concurrent code. The API itself is centered around `StructuredTaskScope`, which allows us to define a clear hierarchy of tasks and subtasks, ensuring that all subtasks are completed or cancelled before the parent task exits. This enforces a structured flow of execution, similar to single-threaded code, where subtasks are confined to the lexical scope of their parent task. The API also provides built-in shutdown policies (e.g., `ShutdownOnFailure` and `ShutdownOnSuccess`) to handle common concurrency patterns, such as cancelling all subtasks if one fails or succeeds. We can also define our own shutdown policies.

By reifying the task-subtask relationship at runtime, structured concurrency makes it easier for us to reason about and debug concurrent programs. It also integrates well with observability tools, such as thread dumps, which can now display the hierarchical structure of tasks and subtasks.

This enhancement does not aim to replace existing concurrency constructs like `ExecutorService` or `Future`, but rather to complement them by offering a more structured and reliable alternative for managing concurrent tasks.

Compared to the fifth preview (https://openjdk.org/jeps/505[JEP 505]), there's on change: the addition of an `onTimeout` method on the `Joiner interface` which allows an implementation to result in case a timeout occurs.
The architects also hope to gather more feedback on the changes made in t0t (chiefly the replacement of the public constructors of StructuredTaskScopewith static factory methods).

== HotSpot

=== https://openjdk.org/jeps/522[JEP 522: G1 GC: Improve Throughput by Reducing Synchronization]

The goal is to increase the average application throughput when the default G1 garbage collector is being used.

This will be achieved by reducing the synchronization overhead between threads and reducing the size of the injected code for write barriers while making sure that the overall architecture of G1 is maintained.

== Language specification

== Security

== Thoughts

== Migrating

=== Applets

This API has been removed as part of https://https://openjdk.org/jeps/504[JEP 504], so if you rely on this you will need to migrate to a different API. For example, the `AWT` API contains several alternatives for the `Applet` class.

I you're casting the result of a `java.net.URLConnection` `getContent()` method to `java.applet.AudioClip` will need to be adapted to the ne return type determined by the JDK's built in content handlers.

== Resources

Some useful resources to dive deeper into the Java ecosystem and stay up to date are:

* https://github.com/SimonVerhoeven/java26-demo[GitHub repository] - this article's code
* https://jdk.java.net/26/release-notes[The release notes] - The official source for all changes, including new features, bug fixes, and deprecations
* https://javaalmanac.io/jdk/26/[The Java version almanac] - A great resource with details on distributions, and API differences between various releases
* https://foojay.io/[Foojay] - A magnificent Java community offering articles, tutorials, and discussions on the latest in the Java ecosystem
* https://sdkman.io/[SDKman!] - a great tool to manage the installation of various tools and languages
* https://inside.java/[Inside Java] - News updates by Java team members at Oracle
* https://www.jcp.org/[Java Community Process] - the place where people can propose, discuss, and approve new features through a Java Specification Request (JSR)