= Java 26
:toc:
:toc-placement:
:toclevels: 3
:icons: font

Java 26 will be released on the Xth of March 2026, and once again it helps move the language forwards.

[NOTE]
.Teaser of enhancements
====

====

== Why Upgrade?

Java 26 offers enterprises:

== Core

=== https://openjdk.org/jeps/504[JEP 504: Remove the Applet API]

The `Applet` API which was deprecated in JDK 17 through https://openjdk.org/jeps/398[JEP 398].
Generally speaking this will have a negligible impact given that web browsers no longer support applets.

The following will be removed:

* `java.applet` package
* `java.beans.AppletInitializer`
* `javax.swing.JApplet`

Additionally, references to the above will be removed from:

* `java.beans.Beans`
* `javax.swing.RepaintManager`

=== https://openjdk.org/jeps/517[JEP 517: HTTP/3 for the HTTP Client API]

The https://en.wikipedia.org/wiki/HTTP/3[HTTP/3 protocol] will now be supported by the https://cr.openjdk.org/~dfuchs/8291976/apidoc.04/api/java.net.http/java/net/http/HttpClient.html[HTTP Client API], allowing us to easily interact with HTTP/3 servers with minimal changes.
The https://en.wikipedia.org/wiki/QUIC[QUIC protocol] will not receive an API through this JEP, nor a sever-side implementation.

This can be done for all requests by configuring it on the HttpClient object:

[source,Java]
----
HttpClient client = HttpClient.newBuilder()
   .version(HttpClient.Version.HTTP_3)
   .build();
----

Or on a request basis:

[source,Java]
----
HttpRequest request = HttpRequest.newBuilder(URI.create("https://github.com/SimonVerhoeven/java26-demo"))
                         .version(HttpClient.Version.HTTP_3)
                         .GET().build();
----

== HotSpot

=== https://openjdk.org/jeps/522[JEP 522: G1 GC: Improve Throughput by Reducing Synchronization]

The goal is to increase the average application throughput when the default G1 garbage collector is being used.

This will be achieved by reducing the synchronization overhead between threads and reducing the size of the injected code for write barriers while making sure that the overall architecture of G1 is maintained.

== Language specification

== Security

== Thoughts

== Migrating

=== Applets

This API has been removed as part of https://https://openjdk.org/jeps/504[JEP 504], so if you rely on this you will need to migrate to a different API. For example, the `AWT` API contains several alternatives for the `Applet` class.

I you're casting the result of a `java.net.URLConnection` `getContent()` method to `java.applet.AudioClip` will need to be adapted to the ne return type determined by the JDK's built in content handlers.

== Resources

Some useful resources to dive deeper into the Java ecosystem and stay up to date are:

* https://github.com/SimonVerhoeven/java26-demo[GitHub repository] - this article's code
* https://jdk.java.net/26/release-notes[The release notes] - The official source for all changes, including new features, bug fixes, and deprecations
* https://javaalmanac.io/jdk/26/[The Java version almanac] - A great resource with details on distributions, and API differences between various releases
* https://foojay.io/[Foojay] - A magnificent Java community offering articles, tutorials, and discussions on the latest in the Java ecosystem
* https://sdkman.io/[SDKman!] - a great tool to manage the installation of various tools and languages
* https://inside.java/[Inside Java] - News updates by Java team members at Oracle
* https://www.jcp.org/[Java Community Process] - the place where people can propose, discuss, and approve new features through a Java Specification Request (JSR)